name: fastppt
description: "A new Flutter project for MacOS PowerPoint shortcuts."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  path_provider: ^2.1.4
  sqflite: ^2.2.0+3
  vector_math: ^2.1.2
  flutter_local_notifications: ^17.2.2
  langchain: ^0.7.5
  langchain_core: ^0.3.5
  langchain_ollama: ^0.3.1
  langchain_chroma: ^0.2.1+2
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
