name: fastppt
description: "A new Flutter project for MacOS PowerPoint shortcuts."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  path_provider: ^2.0.11
  sqflite: ^2.2.0+3
  vector_math: ^2.1.2
  flutter_local_notifications: ^9.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
